### ISSUE TITLE
New upstream feature

### ISSUE THREAD

**Issue by amaanq** [stadelmanma/tree-sitter-fortran#93] opened 2023-08-12 15:34 UTC
Not a bug, but I've added functionality upstream to allow for the case-insensitive regex flag, so `/foo/i` would work now. Hope it might help here.

**Comment by ZedThree** [comment] 2024-04-05 16:07
I've had a stab at switching to this, and although it does make the grammar easier to read, it introduces some errors, mostly around disambiguating plain identifiers and Fortran's unreserved keywords. Unfortunately, these do crop up in the real world.

See [my branch](https://github.com/ZedThree/tree-sitter-fortran/tree/case-insensitive-regex) for implementation, and [this test file](https://github.com/stadelmanma/tree-sitter-fortran/files/14887404/regressions.txt) for some regressions.

One issue I realised is that we can't simply replace, for example, `whiteSpacedKeyword('else', 'if')` with just `/end *if/i` because it's possible to put a continuation line in between the keywords, but this is an orthogonal issue.

**Comment by stadelmanma** [comment] 2024-09-26 15:59
Closing since Fortran's language quirks cause issues.

**Closed by stadelmanma** 2024-09-26 15:59 UTC
Labels: refactor
